# Generated by Django 2.2.1 on 2019-05-29 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('brand_name',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('no_customer', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('group_name',),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('company', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('fax', models.TextField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_id', to='Application.Group')),
            ],
            options={
                'ordering': ('person_type',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_image', models.ImageField(max_length=254, upload_to='')),
                ('description', models.TextField(max_length=100)),
                ('quality', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('supplier_price', models.IntegerField()),
                ('create_date', models.DateField()),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='Application.Brand')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='Application.Person')),
            ],
            options={
                'ordering': ('product_name',),
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('tags_name',),
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('type_name',),
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('amount_paid', models.IntegerField()),
                ('paid', models.IntegerField()),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_id', to='Application.Person')),
            ],
            options={
                'ordering': ('person_id',),
            },
        ),
        migrations.CreateModel(
            name='SaleDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product_price', models.IntegerField()),
                ('sub_total', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saledetails_id', to='Application.Product')),
                ('sales_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saledetails_id', to='Application.Sales')),
            ],
            options={
                'ordering': ('product_id',),
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('opening_balance', models.IntegerField()),
                ('note', models.CharField(max_length=200)),
                ('opening_time', models.DateTimeField(auto_now_add=True)),
                ('closing_time', models.DateTimeField(auto_now_add=True)),
                ('expected', models.IntegerField()),
                ('counted', models.IntegerField()),
                ('difference', models.IntegerField()),
                ('cash_payment_received', models.IntegerField()),
                ('store_credit', models.IntegerField()),
                ('total', models.IntegerField()),
                ('closing_note', models.CharField(max_length=200)),
                ('sales_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_id', to='Application.Sales')),
            ],
            options={
                'ordering': ('status',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='Application.Tags'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='Application.Type'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('suburb', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('post_code', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_id', to='Application.Person')),
            ],
            options={
                'ordering': ('road',),
            },
        ),
    ]
